apiVersion: v1
clusters:
- cluster:
    server: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
  name: openshift-sandbox
contexts:
- context:
    cluster: openshift-sandbox
    namespace: danielgallardo21-dev
    user: danielgallardo21/openshift-sandbox
  name: danielgallardo21-dev/openshift-sandbox/danielgallardo21
current-context: danielgallardo21-dev/openshift-sandbox/danielgallardo21
kind: Config
preferences: {}
users:
- name: danielgallardo21/openshift-sandbox
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args: ["-c", "source ~/script.sh"]
      command: bash
      interactiveMode: IfAvailable
      provideClusterInfo: false